config/routes.rb
Postevent::Application.routes.draw do
  resource :session
  resources :users
  resources :events
  resources :sigs
  resources :locations

  root :to => "users#authorize"
  match 'logout', :to => 'sessions#destroy', :as => "logout"
  match 'users/:id/reset_password' => 'users#reset_password', :as => :reset_password
  match 'authorize', :to => 'users#authorize', :as => "authorize"
  match 'accept', :to => 'users#accept', :as => "accept"

  match 'session/connect/slack', :to => 'sessions#connect_slack'

  mount API => '/'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  attr_accessible :email, :password, :password_confirmation, :slack_user_id
  has_secure_password
  validates :email, :presence => true, :uniqueness => true, :length => {:maximum => 255}
  validates :password, :length => {:maximum => 255}
  validates_presence_of :password, :on => :create
end

app/controllers/users_controller.rb
require 'logger'

class UsersController < ResourceController
  AUTHORIZE_URI = Rails.configuration.post_url + '/authorize'
  ACCEPT_URI = Rails.configuration.post_url + '/accept'
  START_URI = Rails.configuration.post_url + '/events/new'

  def create
    @password = random_password
    params[resource_parameter][:password] = @password
    params[resource_parameter][:password_confirmation] = @password
    if super
      UserMailer.registration_confirmation(@resource, @password).deliver 
    end
  end
  
  def reset_password
    @resource = resource_class.find(params[:id])
    @password = random_password
    @resource.password = @password
    @resource.password_confirmation = @password
    @resource.save
    UserMailer.registration_confirmation(@resource, @password).deliver 
    flash[:notice] = "Password has been reset.  New password has been emailed to user."
    redirect_to :action => "index"
  end

# Oauth authorization

  def authorize
    if Rails.configuration.meetup_consumer_key == nil || System.first.meetup_access_token
      logger.debug("User id in user#authorize #{session[:user_id]}")
      redirect_to START_URI
	else
      #Redirect your user in order to authenticate
      redirect_to MeetupService.new.get_authorization_url(ACCEPT_URI)
    end
  end
 
  # This method will handle the callback once the user authorizes your application
  def accept
    if params[:error]
      redirect_to AUTHORIZE_URI
    else
      if MeetupService.new.authorize(params[:code], ACCEPT_URI)
        redirect_to START_URI
      else
      	redirect_to_AUTHORIZE_URI
      end
    end
  end
  
private
  
  def random_password
    (0...8).map{(65+rand(25)).chr}.join
  end
  
  def resource_class
    User
  end
  
  def order_by
    'email'
  end
  
  def create_user
  end
  
  def validate_delete(resource)
    (resource.events == nil || resource.events.empty?) ? nil : 'Cannot delete User if he/she has events.'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @resource do |f| %>
  <% if @resource.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @resource.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %>*<br />
    <%= f.text_field :email, :size => 40, :maxlength => 255 %>
  </p>
  <p>
    <%= f.label :password %>*<br />
    <%= f.password_field :password, :size => 10, :maxlength => 255  %>
  </p>
  <p>
    <%= f.label :password_confirmation %>*<br />
    <%= f.password_field :password_confirmation, :size => 10, :maxlength => 255  %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

<script type="text/javascript">
	focusField('user_email');
</script>

app/views/users/edit.html.erb
<div class="form">
	<h1>Edit User</h1>
	
	<%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="list">
	<h1>
		Users
		<%= link_to '<i title="New User" class="fa fa-plus"></i>'.html_safe, new_user_path %>
	</h1>
	<table>
	  <tr>
	    <th>Email</th>
	  </tr>
	<% @resources.each do |resource| %>
	  <tr>
	    <td>
		    <%= resource.email %>
		    <%= link_to '<i title="Edit" class="fa fa-edit"></i>'.html_safe, edit_user_path(resource) %>
		    <%= link_to '<i title="Delete" class="fa fa-trash"></i>'.html_safe, resource, :confirm => 'Are you sure?', :method => :delete if resource != current_user && (resource.events == nil || resource.events.empty?) %>
		    <%= link_to '<i title="Reset Password" class="fa fa-key"></i>'.html_safe, reset_password_url(:id => resource.id), :confirm => 'Are you sure?' if resource != current_user %>
	    </td>
	  </tr>
	<% end %>
	</table>
</div>

app/views/users/new.html.erb
<% if !current_user %>
	<div class="edit-screen-background">
		<div class="edit-screen">
			<%= image_tag("AgileAustinLogo.png", :alt => "Agile Austin", :style => "margin-top: 30px") %>
			<h1 style="margin-top: 10px">PostEvent</h1>
			<h3>Add Initial User</h3>
<% else %>
	<div class="form">
		<h1>Add User</h1>
<% end %>
<div class="description">
	New user will be emailed a temporary password.
</div>

<%= form_for @resource do |f| %>
  <% if @resource.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @resource.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %>*<br />
    <%= f.text_field :email, :size => 40, :maxlength => 255 %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

<% if !current_user %>
		</div>
	</div>
<% else %>
	</div>
<% end %>

<script type="text/javascript">
	focusField('user_email');
</script>