config/routes.rb
Postevent::Application.routes.draw do
  resource :session
  resources :users
  resources :events
  resources :sigs
  resources :locations

  root :to => "users#authorize"
  match 'logout', :to => 'sessions#destroy', :as => "logout"
  match 'users/:id/reset_password' => 'users#reset_password', :as => :reset_password
  match 'authorize', :to => 'users#authorize', :as => "authorize"
  match 'accept', :to => 'users#accept', :as => "accept"

  match 'session/connect/slack', :to => 'sessions#connect_slack'

  mount API => '/'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  belongs_to :sig
  belongs_to :location
  attr_accessible :user_id, :date, :start, :end, :title, :sig_id, :location_id, :description, :capacity, :food_sponsor, :speaker, :speaker_bio, :special_instructions
  validates :date, :presence => true
  validates :start, :presence => true
  validates :end, :presence => true
  validates :title, :presence => true, :length => {:maximum => 255}
  validates :description, :presence => true, :length => {:maximum => 65536}
  validates :capacity, :presence => true
  validates :food_sponsor, :presence => true, :length => {:maximum => 255}
  validates :speaker, :length => {:maximum => 255}
  validates :speaker_bio, :length => {:maximum => 65536}
  validates :special_instructions, :length => {:maximum => 65536}
  validates :sig, :presence => true
  validates :location, :presence => true
  validate :validate_date

  def initialize(attributes={})
    date_time_attributes_hack(attributes)
    super(attributes)
  end

  def update_attributes(attributes={})
    date_time_attributes_hack(attributes)
    super(attributes)
  end

  def group_title
    sig.name + " - " + title
  end

  def meetup_url
    if Rails.configuration.meetup_group_urlname
      if meetup_id
        "http://www.meetup.com/" + Rails.configuration.meetup_group_urlname + "/events/" + meetup_id + "/"
      else
        "http://www.meetup.com/" + Rails.configuration.meetup_group_urlname + "/"
      end
    else
        "http://www.meetup.com/"
     end
  end

  def eventbrite_url
    "http://www.eventbrite.com/event/" + (eventbrite_id ? eventbrite_id : '')
  end
  
  def meeting_url
    if meetup_id || !eventbrite_id
      meetup_url
    else
      eventbrite_url
    end
  end

  def validate_date
    errors.add("Date", "must be in future.") unless date.future?
  end

private

  def date_time_attributes_hack(attributes)
    date_hack(attributes, "date")
    time_hack(attributes, "start")
    time_hack(attributes, "end")
  end

  def date_hack(attributes, property)
    keys, values = [], []
    attributes.each_key {|k| keys << k if k =~ /#{property}/ }.sort
    keys.each { |k| values << attributes[k]; attributes.delete(k); }
    attributes[property] = values.join("-")
  end

  def time_hack(attributes, property)
    keys, values = [], []
    attributes.each_key {|k| keys << k if k =~ /#{property}/ }.sort
    keys.each { |k| values << attributes[k]; attributes.delete(k); }
    attributes[property] = values.join(":")
  end
end

app/controllers/events_controller.rb
require 'logger'

class EventsController < ResourceController
  def new
    warn_not_authenticated
    super
  end
  
  def create
    params[resource_parameter][:user_id] = current_user.id
    if super
      errors = []
      EventbriteService.new.create(@resource, errors)
      MeetupService.new.create(@resource, errors, nil, params[:update_mailing_list])
      ManualMailer.event_submitted(@resource, {:prefix => "Posted: "}).deliver 
      GoogleCalendarService.new.create(@resource, errors)
      WordpressService.new.create(@resource, errors)
      if params[:update_mailing_list]
        if Rails.configuration.community_email
          CommunityMailer.event_submitted(@resource).deliver
        end
        TwitterService.new.create(@resource, errors)
      end
      if !errors.empty?
        ErrorMailer.errors(errors, "Posting").deliver
      end
    end
  end

  def edit
    @is_change = true
    warn_not_authenticated
    super
  end

  def update
    if super
      errors = []
      EventbriteService.new.update(@resource, errors)
      MeetupService.new.update(@resource, errors)
      ManualMailer.event_submitted(@resource, {:prefix => "Updated: "}).deliver 
      GoogleCalendarService.new.update(@resource, errors)
      WordpressService.new.update(@resource, errors)
      if params[:update_mailing_list]
        if Rails.configuration.community_email
          CommunityMailer.event_submitted(@resource, {:prefix => "Updated: "}).deliver 
        end
        TwitterService.new.update(@resource, errors)
      end
      if !errors.empty?
        ErrorMailer.errors(errors, "Updating").deliver
      end
    end
  end

private

  def resource_class
    Event
  end
  
  def order_by
    'date, start'
  end

  def new_resource
    @resource = super
    @resource.food_sponsor = Rails.configuration.default_food_sponsor
    @resource.start = Time.local(2012,1,1,12,0)
    @resource.end = Time.local(2012,1,1,13,0)
    @resource
  end  

  def warn_not_authenticated
    logger.debug("events#warn_not_authenticated user id #{session[:user_id]}")
    if Rails.configuration.meetup_consumer_key != nil && !System.first.meetup_access_token
      flash[:unauthorized] = 'Warning: You have not authorized Postevent to post to MeetUp.'
    end
  end
  
  def created_message
    super + " Posted to Meetup" + (params[:update_mailing_list] ? ", Google calendar, Twitter and mailing list." : " and Google calendar.")
  end
  
  def updated_message
    super + " Updated on Meetup and Google calendar." + (params[:update_mailing_list] ? " Reposted to Twitter and mailing list." : "")
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @resource do |f| %>
  <% if @resource.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @resource.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= check_box_tag :update_mailing_list, 1, true %> Send To Mailing List / Twitter?
  <p>
    <%= f.label :title %>*<br />
    <%= f.text_field :title, :maxlength => 50, :size => 40 %>
  </p>
  <p>
    <%= f.label :sig_id %>*<br />
    <%= f.collection_select :sig_id, Sig.order('name'), :id, :name, :include_blank => true %>
  </p>
  <p>
    <%= f.label :description %>*<br />
    <%= f.text_area :description, :size => "80x10", :maxlength => 65536 %>
  </p>
  <p>
    <%= f.label :date %>*<br />
    <%= f.date_select :date, :start_year => Date.today.year, :prompt => {:month => "Month", :day => "Day"} %>
  </p>
  <p>
    <%= f.label :start %>*<br />
    <%= f.time_select :start, :minute_step => 15, :ampm => true, :ignore_date => true %>
  </p>
  <p>
    <%= f.label :end %>*<br />
    <%= f.time_select :end, :minute_step => 15, :ampm => true, :ignore_date => true %>
  </p>
  <p>
    <%= f.label :location %>*<br />
    <%= f.collection_select :location_id, Location.order('name'), :id, :name, :include_blank => true %>
  </p>
  <p>
    <%= f.label :capacity %>*<br />
    <%= f.text_field :capacity, :maxlength => 255, :size => 3, :onkeypress => "return enforceIntegersOnly(event)" %>
  </p>
  <p>
    <%= f.label :food_sponsor %>*<br />
    <%= f.text_field :food_sponsor, :maxlength => 255, :size => 40 %>
  </p>
  <p>
    <%= f.label :speaker %><br />
    <%= f.text_field :speaker, :maxlength => 255, :size => 40 %>
  </p>
  <p>
    <%= f.label :speaker_bio %><br />
    <%= f.text_area :speaker_bio, :size => "80x10", :maxlength => 65536 %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

<script type="text/javascript">
	focusField('event_title');
</script>

app/views/events/edit.html.erb
<div class="form">
	<h1>Edit Event</h1>
	
	<%= render 'form' %>
</div>

app/views/events/index.html.erb
<div class="list">
	<h1>
		Events
		<%= link_to '<i title="New Event" class="fa fa-plus"></i>'.html_safe, new_event_path %>
	</h1>
	<table>
	  <tr>
	    <th>Date</th>
	    <th>Start Time</th>
	    <th>SIG</th>
	    <th>Title</th>
	    <th>Location</th>
	  </tr>
	<% @resources.sort_by{ |obj| obj.date }.reverse.each do |resource| %>
	  <tr>
	    <td><%= resource.date %></td>
	    <td><%= resource.start.hour %>:<%= (resource.start.min < 10 ? "0" : "") + resource.start.min.to_s %></td>
	    <td><%= resource.sig.name %></td>
	    <td>
		    <%= resource.title %>
		    <%= link_to '<i title="Edit" class="fa fa-edit"></i>'.html_safe, edit_event_path(resource) %>
	    </td>
	    <td><%= resource.location.name %></td>
	  </tr>
	<% end %>
	</table>
</div>

app/views/events/new.html.erb
<div class="form">
	<h1>Add Event</h1>
	
	<%= render 'form' %>
</div>