config/routes.rb
Postevent::Application.routes.draw do
  resource :session
  resources :users
  resources :events
  resources :sigs
  resources :locations

  root :to => "users#authorize"
  match 'logout', :to => 'sessions#destroy', :as => "logout"
  match 'users/:id/reset_password' => 'users#reset_password', :as => :reset_password
  match 'authorize', :to => 'users#authorize', :as => "authorize"
  match 'accept', :to => 'users#accept', :as => "accept"

  match 'session/connect/slack', :to => 'sessions#connect_slack'

  mount API => '/'

end

app/models/sig.rb
class Sig < ActiveRecord::Base
  has_many :events
  attr_accessible :email, :google_group, :name
  validates :name, :presence => true, :uniqueness => true, :length => {:maximum => 255}
  validates :google_group, :length => {:maximum => 255}
  validates :name, :length => {:maximum => 255}
  
  def wordpress_category
    name.downcase.gsub(/ /,'-')
  end
end

app/controllers/sigs_controller.rb
class SigsController < ResourceController
  def resource_class
    Sig
  end
  
  def validate_delete(resource)
    (resource.events == nil || resource.events.empty?) ? nil : 'Cannot delete SIG if it has events.'
  end
end

app/views/sigs/_form.html.erb
<%= form_for @resource do |f| %>
  <% if @resource.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @resource.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %>*<br />
    <%= f.text_field :name, :size => 40, :maxlength => 255  %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email, :size => 40, :maxlength => 255  %>
  </p>
  <p>
    <%= f.label :google_group %><br />
    <%= f.text_field :google_group, :size => 40, :maxlength => 255  %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

<script type="text/javascript">
	focusField('sig_name');
</script>

app/views/sigs/edit.html.erb
<div class="form">
	<h1>Edit SIG</h1>
	
	<%= render 'form' %>
</div>

app/views/sigs/index.html.erb
<div class="list">
	<h1>
		SIGs
		<%= link_to '<i title="New SIG" class="fa fa-plus"></i>'.html_safe, new_sig_path %>
	</h1>
	<table>
	  <tr>
	    <th>Name</th>
	  </tr>
	 
	<% @resources.each do |resource| %>
	  <tr>
	    <td>
		    <%= resource.name %>
		    <%= link_to '<i title="Edit" class="fa fa-edit"></i>'.html_safe, edit_sig_path(resource) %>
		    <%= link_to '<i title="Delete" class="fa fa-trash"></i>'.html_safe, resource, :confirm => 'Are you sure?', :method => :delete if (resource.events == nil || resource.events.empty?) %>
	    </td>
	  </tr>
	<% end %>
	</table>
</div>

app/views/sigs/new.html.erb
<div class="form">
	<h1>Add SIG</h1>
	
	<%= render 'form' %>
</div>