config/routes.rb
Postevent::Application.routes.draw do
  resource :session
  resources :users
  resources :events
  resources :sigs
  resources :locations

  root :to => "users#authorize"
  match 'logout', :to => 'sessions#destroy', :as => "logout"
  match 'users/:id/reset_password' => 'users#reset_password', :as => :reset_password
  match 'authorize', :to => 'users#authorize', :as => "authorize"
  match 'accept', :to => 'users#accept', :as => "accept"

  match 'session/connect/slack', :to => 'sessions#connect_slack'

  mount API => '/'

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :events
  attr_accessible :name, :address, :address2, :city, :state, :postal_code, :directions
  validates :name, :presence => true, :uniqueness => true, :length => {:maximum => 255}
  validates :address, :presence => true, :length => {:maximum => 255}
  validates :address2, :length => {:maximum => 255}
  validates :city, :presence => true, :length => {:maximum => 255}
  validates :state, :presence => true, :length => {:maximum => 2}
  validates :postal_code, :length => {:maximum => 255}
  validates :directions, :length => {:maximum => 65536}
  
  def full_address
    address + (address2 && !address2.strip.empty? ? (', ' + address2) : '') + ', ' + city + ', ' + state + ' ' + postal_code
  end

  def name_and_address
    name + ', ' + full_address
  end
end

app/controllers/locations_controller.rb
class LocationsController < ResourceController
  def create
    if super
      EventbriteService.new.create_venue(@resource)
    end
  end

  def update
    if super
      EventbriteService.new.update_venue(@resource)
      MeetupService.new.update_venue(@resource)
    end
  end

  def resource_class
    Location
  end
  
  def validate_delete(resource)
    resource.events.empty? ? nil : 'Cannot delete Location if it has events.'
  end
  
  def new_resource
    @resource = super
    @resource.city = Rails.configuration.default_city
    @resource.state = Rails.configuration.default_state
    @resource
  end  
end

app/views/locations/_form.html.erb
<%= form_for @resource do |f| %>
  <% if @resource.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @resource.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %>*<br />
    <%= f.text_field :name, :size => 40, :maxlength => 255  %>
  </p>
  <p>
    <%= f.label :address %>*<br />
    <%= f.text_field :address, :size => 40, :maxlength => 255  %>
  </p>
  <p>
    <%= f.label :address2 %><br />
    <%= f.text_field :address2, :size => 40, :maxlength => 255  %>
  </p>
  <p>
    <%= f.label :city %>*<br />
    <%= f.text_field :city, :size => 40, :maxlength => 255  %>
  </p>
  <p>
    <%= f.label :state %>*<br />
    <%= f.text_field :state, :size => 2, :maxlength => 2  %>
  </p>
  <p>
    <%= f.label :postal_code %><br />
    <%= f.text_field :postal_code, :size => 10, :maxlength => 255  %>
  </p>
  <p>
    <%= f.label :directions %><br />
    <%= f.text_area :directions, :size => "80x10", :maxlength => 65536 %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

<script type="text/javascript">
	focusField('location_name');
</script>

app/views/locations/edit.html.erb
<div class="form">
	<h1>Edit Location</h1>
	
	<%= render 'form' %>
</div>

app/views/locations/index.html.erb
<div class="list">
	<h1>
		Locations
		<%= link_to '<i title="New Location" class="fa fa-plus"></i>'.html_safe, new_location_path %>
	</h1>
	<table>
	  <tr>
	    <th>Name</th>
	  </tr>
	 
	<% @resources.each do |resource| %>
	  <tr>
	    <td>
		    <%= resource.name %>
		    <%= link_to '<i title="Edit" class="fa fa-edit"></i>'.html_safe, edit_location_path(resource) %>
		    <%= link_to '<i title="Delete" class="fa fa-trash"></i>'.html_safe, resource, :confirm => 'Are you sure?', :method => :delete if (resource.events == nil || resource.events.empty?) %>
	    </td>
	  </tr>
	<% end %>
	</table>
</div>

app/views/locations/new.html.erb
<div class="form">
	<h1>Add Location</h1>
	
	<%= render 'form' %>
</div>